---
name: Linting

on:   # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "stable", "release/v*"]

permissions:
  contents: read

jobs:
  yaml:
    name: YAML Lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: khiemdoan/yaml-linting-action@v1

  ansible:
    name: Ansible Lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: ansible/ansible-lint@v25
